version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - dupl
    - errname
    - exhaustive
    - gochecknoinits
    - gosec
    - lll
    - nolintlint
    - predeclared
    - revive
    - unconvert
    - unparam
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    lll:
      line-length: 200
      tab-width: 4
    nolintlint:
      require-explanation: true
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb.*\.go
      - .*_test\.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/CrowdStrike
  exclusions:
    generated: lax
    paths:
      - .*\.pb.*\.go
      - .*_test\.go
      - third_party$
      - builtin$
      - examples$
