name: Validate Goreleaser Config

on:
  pull_request:
    paths:
      - '.goreleaser.yml'

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Run 'goreleaser check'
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check
