name: lint-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          github-token: ${{ github.token }}

      - name: test
        run: go test -v -race ./...

      - name: build
        run: go build .
